---
- name: Get newest pacman mirrorlist
  ansible.builtin.get_url:
    url: "{{ packages_pacman_mirrorlist_url }}"
    dest: /etc/pacman.d/mirrorlist
    mode: 0644
    owner: root
    group: root
  when: (packages_pacman_update_mirrorlist) and
        (packages_pacman_mirrorlist_url | length > 0)
  register: get_newest_pacman_mirrorlist
  notify:
  - Setup pacman mirrorlist
  - Update pacman cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Update pacman cache
  community.general.pacman:
    update_cache: "{{ packages_update_cache | bool }}"
  when: get_newest_pacman_mirrorlist is skipped
