---
- name: Include os specific pre-tasks
  include_tasks: "{{ ansible_os_family }}-pre.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages_install.all }}"
    state: present
  when: packages_install.all is defined

- name: Install os specific packages
  include_tasks: "{{ ansible_os_family }}-install.yml"

- name: Remove packages
  ansible.builtin.package:
    name: "{{ packages_uninstall.all }}"
    state: absent
  when: packages_uninstall.all is defined

- name: Remove os specific packages
  include_tasks: "{{ ansible_os_family }}-uninstall.yml"
