---
- name: Setup pacman mirrorlist
  ansible.builtin.replace:
    path: /etc/pacman.d/mirrorlist
    regexp: ^#Server
    replace: Server

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
